<?php
/**
 * @file
 * Hooks implementations for the GraphicsMagick module.
 */

declare(strict_types=1);


/**
 * Implements hook_autoload_info().
 */
function graphicsmagick_autoload_info(): array {
  return array(
    'BlurEffect' => 'includes/blur_effect.class.inc',
    'BlurOperation' => 'includes/blur_operation.class.inc',
    'Color' => 'includes/color.class.inc',
    'CropOperation' => 'includes/crop_operation.class.inc',
    'DefaultSetting' => 'includes/default_setting.class.inc',
    'DesaturateOperation' => 'includes/desaturate_operation.class.inc',
    'DespeckleEffect' => 'includes/despeckle_effect.class.inc',
    'DespeckleOperation' => 'includes/despeckle_operation.class.inc',
    'EdgeEffect' => 'includes/edge_effect.class.inc',
    'EdgeOperation' => 'includes/edge_operation.class.inc',
    'EffectBase' => 'includes/effect_base.class.inc',
    'EffectInterface' => 'includes/effect_interface.class.inc',
    'EmbossEffect' => 'includes/emboss_effect.class.inc',
    'EmbossOperation' => 'includes/emboss_operation.class.inc',
    'EnhanceEffect' => 'includes/enhance_effect.class.inc',
    'EnhanceOperation' => 'includes/enhance_operation.class.inc',
    'EqualizeEffect' => 'includes/equalize_effect.class.inc',
    'EqualizeOperation' => 'includes/equalize_operation.class.inc',
    'FileException'=> 'includes/file_exception.class.inc',
    'FileWriteException'=> 'includes/file_write_exception.class.inc',
    'FlipEffect' => 'includes/flip_effect.class.inc',
    'FlipOperation' => 'includes/flip_operation.class.inc',
    'FlopEffect' => 'includes/flop_effect.class.inc',
    'FlopOperation' => 'includes/flop_operation.class.inc',
    'GammaEffect' => 'includes/gamma_effect.class.inc',
    'GammaOperation' => 'includes/gamma_operation.class.inc',
    'ImageHandler' => 'includes/image_handler.class.inc',
    'NoiseEffect' => 'includes/noise_effect.class.inc',
    'NoiseOperation' => 'includes/noise_operation.class.inc',
    'OilPaintEffect' => 'includes/oil_paint_effect.class.inc',
    'OilPaintOperation' => 'includes/oil_paint_operation.class.inc',
    'OperationBase' => 'includes/operation_base.class.inc',
    'OperationInterface' => 'includes/operation_interface.class.inc',
    'OperationParams' => 'includes/effect_operation.class.inc',
    'ResizeOperation' => 'includes/resize_operation.class.inc',
    'RotateOperation' => 'includes/rotate_operation.class.inc',
    'SolarizeEffect' => 'includes/solarize_effect.class.inc',
    'SolarizeOperation' => 'includes/solarize_operation.class.inc',
    'SpreadEffect' => 'includes/spread_effect.class.inc',
    'SpreadOperation' => 'includes/spread_operation.class.inc',
    'SwirlEffect' => 'includes/swirl_effect.class.inc',
    'SwirlOperation' => 'includes/swirl_operation.class.inc',
    'ToolkitInfo' => 'includes/toolkit_info.class.inc',
    'ToolkitInfoInterface' => 'includes/toolkit_info_interface.class.inc',
    'ToolkitSettings' => 'includes/toolkit_settings.class.inc',
    'ToolkitSettingsInterface' => 'includes/toolkit_settings_interface.class.inc',
  );
}

/**
 * Implements hook_image_effect_info().
 */
function graphicsmagick_image_effect_info(): array {
  $effects = array();

  $effects['graphicsmagick_effects_blur'] = array(
    'label' => t('Blur'),
    'help' => t('This effect will make the image details less distinct using a Gaussian operator.'),
    'dimensions passthrough' => TRUE,
    'form callback' => 'graphicsmagick_effects_blur_form',
    'effect callback' => 'graphicsmagick_effects_blur',
    'summary theme' => 'graphicsmagick_effects_blur_summary',
  );

  $effects['graphicsmagick_effects_despeckle'] = array(
    'label' => t('Despeckle'),
    'help' => t('This effect will reduce the speckle noise in an image while preserving the original image edges.'),
    'dimensions passthrough' => TRUE,
    'effect callback' => 'graphicsmagick_effects_despeckle',
  );

  $effects['graphicsmagick_effects_edge'] = array(
    'label' => t('EdgeEffect enhance'),
    'help' => t('This effect will enhance edges within the image with a convolution filter.'),
    'dimensions passthrough' => TRUE,
    'form callback' => 'graphicsmagick_effects_edge_form',
    'effect callback' => 'graphicsmagick_effects_edge',
    'summary theme' => 'graphicsmagick_effects_oil_paint_summary',
  );

  $effects['graphicsmagick_effects_emboss'] = array(
    'label' => t('Emboss'),
    'help' => t('This effect will convolve the image using a Gaussian operator, giving the image a three-dimensional effect.'),
    'dimensions passthrough' => TRUE,
    'form callback' => 'graphicsmagick_effects_emboss_form',
    'effect callback' => 'graphicsmagick_effects_emboss',
    'summary theme' => 'graphicsmagick_effects_blur_summary',
  );

  $effects['graphicsmagick_effects_enhance'] = array(
    'label' => t('Enhance'),
    'help' => t('This effect will improve the quality of a noisy image.'),
    'dimensions passthrough' => TRUE,
    'effect callback' => 'graphicsmagick_effects_enhance',
  );

  $effects['graphicsmagick_effects_equalize'] = array(
    'label' => t('Equalize'),
    'help' => t('This effect will equalize the image histogram.'),
    'dimensions passthrough' => TRUE,
    'effect callback' => 'graphicsmagick_effects_equalize',
  );

  $effects['graphicsmagick_effects_flip'] = array(
    'label' => t('Vertical mirror'),
    'help' => t('This effect will create a vertical mirror image.'),
    'dimensions passthrough' => TRUE,
    'effect callback' => 'graphicsmagick_effects_flip',
  );

  $effects['graphicsmagick_effects_flop'] = array(
    'help' => t('This effect will create a horizontal mirror image.'),
    'dimensions passthrough' => TRUE,
    'effect callback' => 'graphicsmagick_effects_flop',
  );

  $effects['graphicsmagick_effects_gamma'] = array(
    'label' => t('Gamma'),
    'help' => t("This effect will change the gamma values."),
    'dimensions passthrough' => TRUE,
    'form callback' => 'graphicsmagick_effects_gamma_form',
    'effect callback' => 'graphicsmagick_effects_gamma',
    'summary theme' => 'graphicsmagick_effects_gamma_summary',
  );

  $effects['graphicsmagick_effects_noise'] = array(
    'label' => t('Add noise'),
    'help' => t("This effect will add random noise to the image."),
    'dimensions passthrough' => TRUE,
    'form callback' => 'graphicsmagick_effects_noise_form',
    'effect callback' => 'graphicsmagick_effects_noise',
    'summary theme' => 'graphicsmagick_effects_noise_summary',
  );

  $effects['graphicsmagick_effects_oil_paint'] = array(
    'label' => t('Oil paint'),
    'help' => t('This effect will simulate an oil painting.'),
    'dimensions passthrough' => TRUE,
    'form callback' => 'graphicsmagick_effects_oil_paint_form',
    'effect callback' => 'graphicsmagick_effects_oil_paint',
    'summary theme' => 'graphicsmagick_effects_oil_paint_summary',
  );

  $effects['graphicsmagick_effects_solarize'] = array(
    'label' => t('Solarize'),
    'help' => t('SolarizeEffect will apply an effect to the image, similar to the one achieved in a photo darkroom by selectively exposing areas of photo sensitive paper to light.'),
    'dimensions passthrough' => TRUE,
    'form callback' => 'graphicsmagick_effects_solarize_form',
    'effect callback' => 'graphicsmagick_effects_solarize',
    'summary theme' => 'graphicsmagick_effects_solarize_summary',
  );

  $effects['graphicsmagick_effects_spread'] = array(
    'label' => t('Spread'),
    'help' => t('This effect will randomly displace each pixel in a block defined by the radius.'),
    'form callback' => 'graphicsmagick_effects_spread_form',
    'effect callback' => 'graphicsmagick_effects_spread',
    'summary theme' => 'graphicsmagick_effects_oil_paint_summary',
  );

  $effects['graphicsmagick_effects_swirl'] = array(
    'label' => t('Swirl'),
    'help' => t('This effect will swirl the pixels about the center of the image.'),
    'form callback' => 'graphicsmagick_effects_swirl_form',
    'effect callback' => 'graphicsmagick_effects_swirl',
    'summary theme' => 'graphicsmagick_effects_swirl_summary',
  );

  return $effects;
}

 /**
 * Implements hook_image_toolkits().
 */
function graphicsmagick_image_toolkits(): array {
  try {
    $toolkit_info = new ToolkitInfo();
    $available = $toolkit_info->isAvailable();
  }
  catch (RuntimeException $e) {
    watchdog_exception('graphicsmagick', $e);

    $available = FALSE;
  }

  return array(
    'graphicsmagick_toolkit' => array(
      'title' => t('GraphicsMagick toolkit'),
      'available' => $available,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function graphicsmagick_theme(): array {
  $summary_base = array(
    'variables' => array( 'data' => NULL),
    'file' => 'includes/graphicsmagick.theme.inc',
  );

  return array(
    'graphicsmagick_effects_blur_summary' => $summary_base,
    'graphicsmagick_effects_edge_summary' => $summary_base,
    'graphicsmagick_effects_emboss_summary' => $summary_base,
    'graphicsmagick_effects_gamma_summary' => $summary_base,
    'graphicsmagick_effects_noise_summary' => $summary_base,
    'graphicsmagick_effects_oil_paint_summary' => $summary_base,
    'graphicsmagick_effects_solarize_summary' => $summary_base,
    'graphicsmagick_effects_spread_summary' => $summary_base,
    'graphicsmagick_effects_swirl_summary' => $summary_base,
  );
}

/**
 * Retrieves settings for the GraphicsMagick toolkit.
 *
 * @return array
 *   The form array.
 */
function image_graphicsmagick_toolkit_settings(): array {
  $settings = new ToolkitSettings();

  return $settings->settingsForm();
}

/**
 * Retrieves the supported extensions for the GraphicsMagick toolkit.
 *
 * @return array
 *   The supported extensions.
 */
function image_graphicsmagick_toolkit_supported_extensions(): array {
  try {
    $toolkit_info = new ToolkitInfo();

    return $toolkit_info->supportedExtensions();
  }
  catch (RuntimeException $e) {
    watchdog_exception('graphicsmagick', $e);

    return array();
  }
}

/**
 * Loads an image from a file.
 *
 * @param object $image
 *   An image object. The $image->handler and $image->format values will be
 *   populated by this call.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 *
 * @see image_load()
 * @see graphicsmagick_image_load()
 */
function image_graphicsmagick_toolkit_load(object $image): bool {
  return graphicsmagick_image_load($image);
}

/**
 * Writes an image to a destination file.
 *
 * @param object $image
 *   An image object. The $image->handler value will be changed by this call.
 * @param string $destination
 *   A URI or file path where the image should be saved.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 *
 * @see image_save()
 * @see graphicsmagick_image_save()
 */
function image_graphicsmagick_toolkit_save(object $image, string $destination): bool {
  return graphicsmagick_image_save($image, $destination);
}

/**
 * Gets details about an image.
 *
 * @param object $image
 *   An image object.
 *
 * @return false|array
 *   FALSE, if the file could not be found or is not an image. Otherwise, a
 *   keyed array containing information about the image:
 *   - "width": Width, in pixels.
 *   - "height": Height, in pixels.
 *
 * @see image_get_info()
 */
function image_graphicsmagick_toolkit_get_info(object $image): false|array {
  $details = array(
    'width' => 0,
    'height' => 0,
  );

  try {
    $handler = ImageHandler::create($image);
    $details['width'] = $handler->imageWidth();
    $details['height'] = $handler->imageHeight();
  }
  catch (InvalidArgumentException | Error $e) {
    // An exception has been thrown when trying to access the image information,
    // which could also mean the image file is corrupted. Return FALSE to signal
    // an error.
    watchdog_exception('graphicsmagick', $e);

    return FALSE;
  }

  $image->handler = NULL;

  return $details;
}

/**
 * Scales an image to the specified size using the GraphicsMagick library.
 *
 * @param object $image
 *   An image object. The $image->info['width'] and $image->info['height']
 *   values will be modified by this call.
 * @param int $width
 *   The new width of the resized image, in pixels.
 * @param int $height
 *   The new height of the resized image, in pixels.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 *
 * @see image_resize()
 */
function image_graphicsmagick_toolkit_resize(object $image, int $width, int $height): bool {
  if ($operation = OperationBase::create('resize')) {
    return $operation->apply($image, array('width' => $width, 'height' => $height));
  }

  return FALSE;
}

/**
 * Rotates an image the given number of degrees.
 *
 * @param object $image
 *   An image object. The $image->info['width'] and $image->info['height']
 *   values will be modified by this call.
 * @param int $degrees
 *   The number of (clockwise) degrees to rotate the image.
 * @param int|string|null $background
 *   A hexadecimal value specifying the background color to use for the
 *   uncovered area of the image after the rotation, for example 0x000000 for
 *   black or 0xff00ff for magenta. The default value is #FFFFFF.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 *
 * @see image_rotate()
 */
function image_graphicsmagick_toolkit_rotate(object $image, int $degrees, int|string|null $background): bool {
  try {
    $color = Color::toHex($background);

    if ($operation = OperationBase::create('rotate')) {
      return $operation->apply($image, array('degrees' => $degrees, 'background' => $color));
    }
  }
  catch (InvalidArgumentException $e) {
    watchdog_exception('graphicsmagick', $e);
    return FALSE;
  }

  return FALSE;
}

/**
 * Crops an image using the GraphicsMagick library.
 *
 * @param object $image
 *   An image object. The $image->info['width'] and $image->info['height']
 *   values will be modified by this call.
 * @param int $x
 *   The starting x offset at which to start the crop, in pixels.
 * @param int $y
 *   The starting y offset at which to start the crop, in pixels.
 * @param int $width
 *   The width of the cropped area, in pixels.
 * @param int $height
 *   The height of the cropped area, in pixels.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 *
 * @see image_crop()
 */
function image_graphicsmagick_toolkit_crop(object $image, int $x, int $y, int $width, int $height): bool {
  if ($operation = OperationBase::create('crop')) {
    return $operation->apply($image, array('x' => $x, 'y' => $y, 'width' => $width, 'height' => $height));
  }

  return FALSE;
}

/**
 * Converts an image to grayscale.
 *
 * @param object $image
 *   An image object.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 *
 * @see image_desaturate()
 */
function image_graphicsmagick_toolkit_desaturate(object $image): bool {
  if ($operation = OperationBase::create('desaturate')) {
    return $operation->apply($image);
  }

  return FALSE;
}

/**
 * Blurs an image.
 *
 * @param object $image
 *   An image object.
 * @param float $radius
 *   The Gaussian radius.
 * @param float $sigma
 *   The Gaussian sigma.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 */
function image_graphicsmagick_toolkit_blur(object $image, float $radius, float $sigma): bool {
  if ($operation = OperationBase::create('blur')) {
    return $operation->apply($image, array('radius' => $radius, 'sigma' => $sigma));
  }

  return FALSE;
}

/**
 * Reduces the speckle noise in an image.
 *
 * @param object $image
 *   An image object.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 */
function image_graphicsmagick_toolkit_despeckle(object $image): bool {
  if ($operation = OperationBase::create('despeckle')) {
    return $operation->apply($image);
  }

  return FALSE;
}

/**
 * Enhances the image edges.
 *
 * @param object $image
 *   An image object.
 * @param float $radius
 *   The operation radius.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 */
function image_graphicsmagick_toolkit_edge(object $image, float $radius): bool {
  if ($operation = OperationBase::create('edge')) {
    return $operation->apply($image, array('radius' => $radius));
  }

  return FALSE;
}

/**
 * Embosses an image.
 *
 * @param object $image
 *   An image object.
 * @param float $radius
 *   The Gaussian radius.
 * @param float $sigma
 *   The Gaussian sigma.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function image_graphicsmagick_toolkit_emboss(object $image, float $radius, float $sigma): bool {
  if ($operation = OperationBase::create('emboss')) {
    return $operation->apply($image, array('radius' => $radius, 'sigma' => $sigma));
  }

  return FALSE;
}

/**
 * Enhances an image.
 *
 * @param object $image
 *   An image object.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to blur the image.
 */
function image_graphicsmagick_toolkit_enhance(object $image): bool {
  if ($operation = OperationBase::create('enhance')) {
    return $operation->apply($image);
  }

  return FALSE;
}

/**
 * Equalizes an image.
 *
 * @param object $image
 *   An image object.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function image_graphicsmagick_toolkit_equalize(object $image): bool {
  if ($operation = OperationBase::create('equalize')) {
    return $operation->apply($image);
  }

  return FALSE;
}

/**
 * Creates a vertical mirror image.
 *
 * @param object $image
 *   An image object.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function image_graphicsmagick_toolkit_flip(object $image): bool {
  if ($operation = OperationBase::create('flip')) {
    return $operation->apply($image);
  }

  return FALSE;
}

/**
 * Creates a horizontal mirror image.
 *
 * @param object $image
 *   An image object.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function image_graphicsmagick_toolkit_flop(object $image): bool {
  if ($operation = OperationBase::create('flop')) {
    return $operation->apply($image);
  }

  return FALSE;
}

/**
 * Changes the image gamma value.
 *
 * @param object $image
 *   An image object.
 * @param float $gamma
 *   The new gamma value.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function image_graphicsmagick_toolkit_gamma(object $image, float $gamma): bool {
  if ($operation = OperationBase::create('gamma')) {
    return $operation->apply($image, array('gamma' => $gamma));
  }

  return FALSE;
}

/**
 * Adds random noise.
 *
 * @param object $image
 *   An image object.
 * @param int $noise
 *   The noise type.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function image_graphicsmagick_toolkit_noise(object $image, int $noise): bool {
  if ($operation = OperationBase::create('noise')) {
    return $operation->apply($image, array('noise' => $noise));
  }

  return FALSE;
}

/**
 * Image effect callback; simulate an oil painting.
 *
 * @param object $image
 *   An image object.
 * @param float $radius
 *   The radius of the circular region used to calculate the most frequently
 *   used color.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function image_graphicsmagick_toolkit_oil_paint(object $image, float $radius): bool {
  if ($operation = OperationBase::create('oil_paint')) {
    return $operation->apply($image, array('radius' => $radius));
  }

  return FALSE;
}

/**
 * Simulates a solarize effect.
 *
 * @param object $image
 *   An image object.
 * @param int $level
 *   An integer representing the level of the effect.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function image_graphicsmagick_toolkit_solarize(object $image, int $level): bool {
  if ($operation = OperationBase::create('solarize')) {
    return $operation->apply($image, array('level' => $level));
  }

  return FALSE;
}

/**
 * Randomly displaces each pixel in a circular region.
 *
 * @param object $image
 *   An image object.
 *
 * @param float $radius
 *   The radius of the circular region where the pixels are randomly displaced.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function image_graphicsmagick_toolkit_spread(object $image, float $radius): bool {
  if ($operation = OperationBase::create('spread')) {
    return $operation->apply($image, array('radius' => $radius));
  }

  return FALSE;
}

/**
 * Swirls the pixels about the center of the image.
 *
 * @param object $image
 *   An image object.
 * @param float $degrees
 *   The sweep of the arc through which each pixel is moved.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function image_graphicsmagick_toolkit_swirl(object $image, float $degrees): bool {
  if ($operation = OperationBase::create('swirl')) {
    return $operation->apply($image, array('degrees' => $degrees));
  }

  return FALSE;
}

/**
 * Form structure for the blur effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_blur_form(array $data): array {
  if ($effect = EffectBase::create('blur')) {
    return $effect->settingsForm($data);
  }

  return array();
}

/**
 * Image effect callback; blur an image.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when performing the blur effect with the
 *   following items:
 *   - "radius": The Gaussian radius.
 *   - "sigma": The Gaussian sigma.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_blur(object $image, array $data): bool {
  if ($effect = EffectBase::create('blur')) {
    return $effect->apply($image, $data);
  }

  return FALSE;
}

/**
 * Image effect callback; reduce the speckle noise in an image.
 *
 * @param object $image
 *   An image object.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_despeckle(object $image): bool {
  if ($effect = EffectBase::create('despeckle')) {
    return $effect->apply($image);
  }

  return FALSE;
}

/**
 * Form structure for the edge effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   An array of attributes to use when performing the effect with the
 *   following items:
 *   - "radius": the operation radius.
 */
function graphicsmagick_effects_edge_form(array $data): array {
  if ($effect = EffectBase::create('edge')) {
    return $effect->settingsForm($data);
  }

  return array();
}

/**
 * Image effect callback; enhance the image edges.
 *
 * @param object $image
 *   An image object.
 * @param $data
 *   An array of attributes to use when performing the effect with the
 *   following items:
 *   - "radius": the operation radius.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_edge(object $image, array $data): bool {
  if ($effect = EffectBase::create('edge')) {
    return $effect->apply($image, $data);
  }
  return FALSE;
}

/**
 * Form structure for the emboss effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_emboss_form(array $data): array {
  if ($effect = EffectBase::create('emboss')) {
    return $effect->settingsForm($data);
  }

  return array();
}

/**
 * Image effect callback; emboss an image.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when performing the emboss effect with the
 *   following items:
 *   - "radius": The Gaussian radius.
 *   - "sigma": The Gaussian sigma.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_emboss(object $image, array $data): bool {
  if ($effect = EffectBase::create('emboss')) {
    return $effect->apply($image, $data);
  }

  return FALSE;
}

/**
 * Image effect callback; enhance an image.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when enhancing an image. No attributes are
 *   currently used for this effect.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to blur the image.
 */
function graphicsmagick_effects_enhance(object $image, array $data): bool {
  if ($effect = EffectBase::create('enhance')) {
    return $effect->apply($image, $data);
  }

  return FALSE;
}

/**
 * Image effect callback; equalize an image.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when equalizing an image. No attributes are
 *   currently used for this effect.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_equalize(object $image, array $data): bool {
  if ($effect = EffectBase::create('equalize')) {
    return $effect->apply($image, $data);
  }

  return FALSE;
}

/**
 * Image effect callback; create a vertical mirror image.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when creating a vertical mirror image. No
 *   attributes are currently used for this effect.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_flip(object $image, array $data): bool {
  if ($effect = EffectBase::create('flip')) {
    return $effect->apply($image, $data);
  }

  return FALSE;
}

/**
 * Image effect callback; create a horizontal mirror image.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when creating a horizontal mirror image. No
 *   attributes are currently used for this effect.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_flop(object $image, array $data): bool {
  if ($effect = EffectBase::create('flop')) {
    return $effect->apply($image, $data);
  }

  return FALSE;
}

/**
 * Form structure for the gamma effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_gamma_form(array $data): array {
  if ($effect = EffectBase::create('gamma')) {
    return $effect->settingsForm($data);
  }

  return array();
}

/**
 * Image effect callback; change the image gamma value.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when changing the gamma value with the
 *   following items:
 *   - "gamma": The new gamma value.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_gamma(object $image, array $data): bool {
  if ($effect = EffectBase::create('gamma')) {
    return $effect->apply($image, $data);
  }

  return FALSE;
}

/**
 * Form structure for the noise effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_noise_form(array $data): array {
  if ($effect = EffectBase::create('noise')) {
    return $effect->settingsForm($data);
  }

  return array();
}

/**
 * Image effect callback; add random noise.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when applying the effect with the following
 *   items:
 *   - "noise": The noise type.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_noise(object $image, array $data): bool {
  if ($effect = EffectBase::create('noise')) {
    return $effect->apply($image, $data);
  }

  return FALSE;
}

/**
 * Form structure for the oil painting effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_oil_paint_form(array $data): array {
  if ($effect = EffectBase::create('oil_paint')) {
    return $effect->settingsForm($data);
  }

  return array();
}

/**
 * Image effect callback; simulate an oil painting.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when applying the effect with the following
 *   items:
 *   - "radius": The radius of the circular region used to calculate the most
 *     frequently used color.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_oil_paint(object $image, array $data): bool {
  if ($effect = EffectBase::create('oil_paint')) {
    return $effect->apply($image, $data);
  }

  return FALSE;
}

/**
 * Form structure for the solarize effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_solarize_form(array $data): array {
  if ($effect = EffectBase::create('solarize')) {
    return $effect->settingsForm($data);
  }

  return array();
}

/**
 * Image effect callback; simulate a solarize effect.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when applying the effect with the
 *   following items:
 *   - "level": An integer representing the level of the effect.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_solarize(object $image, array $data): bool {
  if ($effect = EffectBase::create('solarize')) {
    return $effect->apply($image, $data);
  }

  return FALSE;
}

/**
 * Form structure for the spread effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_spread_form(array $data): array {
  if ($effect = EffectBase::create('spread')) {
    return $effect->settingsForm($data);
  }

  return array();
}

/**
 * Image effect callback; randomly displace each pixel in a circular region.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when applying the effect with the following
 *   items:
 *   - "radius": The radius of the circular region where the pixels are randomly
 *     displaced.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_spread(object $image, array $data): bool {
  if ($effect = EffectBase::create('spread')) {
    return $effect->apply($image, $data);
  }

  return FALSE;
}

/**
 * Form structure for the swirl effect.
 *
 * Note that this is not a complete form; it only contains the portion of the
 * form for configuring the effect options. Therefore, it does not need to
 * include metadata about the effect, nor a submit button.
 *
 * @param array $data
 *   The current configuration for this effect.
 */
function graphicsmagick_effects_swirl_form(array $data): array {
  if ($effect = EffectBase::create('swirl')) {
    return $effect->settingsForm($data);
  }

  return array();
}

/**
 * Image effect callback; swirl the pixels about the center of the image.
 *
 * @param object $image
 *   An image object.
 * @param array $data
 *   An array of attributes to use when applying the effect with the following
 *   items:
 *   - "degrees": The sweep of the arc through which each pixel is moved.
 *
 * @return bool
 *   TRUE on success, FALSE on failure to apply the effect.
 */
function graphicsmagick_effects_swirl(object $image, array $data): bool {
  if ($effect = EffectBase::create('swirl')) {
    return $effect->apply($image, $data);
  }

  return FALSE;
}

/**
 * Loads an image from a file.
 *
 * This function can be used from any module that needs to use the effects
 * implemented by the GraphicsMagick Effects modules independently of the
 * toolkit set for the site. In the case the used toolkit is not
 * GraphicsMagick Toolkit, this function could cause the image to be loaded
 * again, with the consequence that the image data is loaded twice in memory.
 *
 * $image->source is expected to contain the source file path. If it has not
 * been set, or it does not contain the expected value, this function will
 * return FALSE.
 *
 * @param object $image
 *   An image object. The $image->handler, and $image->format, and
 *   $image->mimeType values will be populated by this call.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 */
function graphicsmagick_image_load(object $image): bool {
  if (isset($image->handler) && !is_a($image->handler, ImageHandler::class)) {
    // $image->handler has been already set, but it is not the expected
    // instance. To avoid conflicts with other modules, avoid to load the image.
    return FALSE;
  }
  elseif (isset($image->handler)) {
    $image->handler = NULL;
  }

  try {
    $handler = ImageHandler::create($image);

    if (!$handler) {
      return FALSE;
    }

    $image->format = $handler->imageFormat();
    $toolkit_info = new ToolkitInfo();
    $image->mimeType = $toolkit_info->mimeTypeFromFormat($image->format);
  }
  catch (RuntimeException $e) {
    watchdog_exception('graphicsmagick', $e);

    return FALSE;
  }

  return TRUE;
}

/**
 * Writes an image to a destination file.
 *
 * @param object $image
 *   An image object. $image->handler must be a Gmagick instance; the image will
 *   be saved and the $image->handler value will be changed by this call.
 * @param string $destination
 *   A URI or file path where the image should be saved.
 *
 * @return bool
 *   TRUE or FALSE, based on success.
 *   The returned value will be FALSE even in the case the $image->handler value
 *   has been set, but it is not a Gmagick instance, or the $image->handler
 *   value has not been set, and it is not possible to load the source image.
 */
function graphicsmagick_image_save(object $image, string $destination): bool {
  $settings = new ToolkitSettings();

  if (isset($image->handler) && !is_a($image->handler, ImageHandler::class)) {
    // $image->handler has been already set, but it is not the expected
    // instance. To avoid conflicts with other modules, avoid to save the image
    // and return FALSE.
    return FALSE;
  }

  if (!isset($image->handler)) {
    return FALSE;
  }

  switch ($image->mimeType) {
    case 'image/jpeg':
      $image->handler->compressionQuality($settings->get('graphicsmagick_toolkit_jpeg_quality'));
      break;

    case 'image/png';
      $image->handler->compressionQuality($settings->get('graphicsmagick_toolkit_png_quality'));
      break;
  }

  return $image->handler->save($destination);
}
