<?php
/**
 * @file
 * Install, update, and uninstall hooks for the GraphicsMagick module.
 */

declare(strict_types=1);

/**
 * Implements hook_requirements().
 *
 * @hook
 */
function graphicsmagick_requirements($phase): array {
  $requirements = array();

  // Ensure translations don't break during installation.
  $t = get_t();

  if (extension_loaded('gmagick') && class_exists('Gmagick')) {
    try {
      $version_array = (new Gmagick)->getVersion();
      $version = $version_array['versionString'] ?? ($version_array['versionNumber'] ?? NULL);

      $requirements['graphicsmagick_extension']['severity'] = REQUIREMENT_OK;
      $requirements['graphicsmagick_extension']['value'] = (isset($version) ? $t('Version: %version', ['%version' => $version]) : $t('Version: unknown'));
      $requirements['graphicsmagick_extension']['description'] = $t(
        'The <a href="@gmagick_link">Gmagick</a> extension has been enabled and loaded.',
        array('@gmagick_link' => 'https://www.php.net/manual/en/book.gmagick.php')
      );
    }
    catch (GmagickException|Error) {
      $requirements['graphicsmagick_extension']['severity'] = REQUIREMENT_ERROR;
      $requirements['graphicsmagick_extension']['value'] = $t('Version: unknown');
      $requirements['graphicsmagick_extension']['description'] = $t(
        'The <a href="@gmagick_link">Gmagick</a> extension has been loaded, but there has been an error when using the class it implements.',
        ['@gmagick_link' => 'https://www.php.net/manual/en/book.gmagick.php']
      );

      return $requirements;
    }

    try {
      $toolkit_info = new ToolkitInfo();

      if ($toolkit_info->isAvailable()) {
        $requirements['graphicsmagick_toolkit']['severity'] = REQUIREMENT_ERROR;
        $requirements['graphicsmagick_toolkit']['value'] = $t('The GraphicsMagick toolkit is available.');
        $requirements['graphicsmagick_toolkit']['description'] = $t(
          'The <a href="@gmagick_link">Gmagick</a> extension has been loaded and can be used with the GraphicsMagick toolkit.',
          ['@gmagick_link' => 'https://www.php.net/manual/en/book.gmagick.php']
        );

        return $requirements;
      }
    }
    catch (RuntimeException $e) {
      watchdog_exception('graphicsmagick', $e);

      $requirements['graphicsmagick_toolkit']['severity'] = REQUIREMENT_ERROR;
      $requirements['graphicsmagick_toolkit']['value'] = $t('Version: unknown');
      $requirements['graphicsmagick_toolkit']['description'] = $t(
        'The <a href="@gmagick_link">Gmagick</a> extension has been loaded, but there has been an error when using the class it implements.',
        ['@gmagick_link' => 'https://www.php.net/manual/en/book.gmagick.php']
      );

      return $requirements;
    }

  }
  else {
    if (!extension_loaded('gmagick')) {
      $requirements['graphicsmagick_extension']['severity'] = REQUIREMENT_ERROR;
      $requirements['graphicsmagick_extension']['value'] = $t('Not found');
      $requirements['graphicsmagick_extension']['description'] = $t(
        'The <a href="@gmagick_link">Gmagick</a> extension is required by the GraphicsMagick module. See the <a href="@gmagick_installation">installation</a> page for more information.',
        [
          '@gmagick_link' => 'https://www.php.net/manual/en/book.gmagick.php',
          '@gmagick_installation' => 'https://www.php.net/manual/en/gmagick.installation.php',
        ]
      );
    }
    elseif (!class_exists('Gmagick')) {
      // In the case the Gmagick extension has been loaded, but the Gmagick
      // class has not found, give a more specific error that explains that.
      $requirements['graphicsmagick_extension']['severity'] = REQUIREMENT_ERROR;
      $requirements['graphicsmagick_extension']['value'] = $t('Not found');
      $requirements['graphicsmagick_extension']['description'] = $t(
        'The <a href="@gmagick_link">Gmagick</a> extension has been loaded, but the <code>Gmagick</code> class it should define has not been found.',
        [
          '@gmagick_link' => 'https://www.php.net/manual/en/book.gmagick.php',
        ]
      );
    }
  }

  if ($phase == 'runtime' && module_exists('graphicsmagick_effects')) {
    // Give a warning if the GraphicsMagick Effects module is installed.
    $path = backdrop_get_path('module', 'graphicsmagick_effects');
    $requirements['graphicsmagick_effects']['title'] = $t('GraphicMagick Effects');
    $requirements['graphicsmagick_effects']['severity'] = REQUIREMENT_WARNING;
    $requirements['graphicsmagick_effects']['value'] = $t('Installed');
    $requirements['graphicsmagick_effects']['description'] = $t(
      'The <em>GraphicsMagick Effects</em> module located at %path is no longer necessary, since its functionality is now provided by the <em>GraphicsMagick</em> module. It is recommended to !operation the <em>GraphicsMagick Effects</em> module from your site.',
      array('!operation' => t('uninstall'), '%path' => BACKDROP_ROOT . "/$path")
    );
  }

  return $requirements;
}

/**
 * Uninstall the GraphicsMagick Effects module.
 *
 * @hook
 */
function graphicsmagick_update_1101(): void {
  if (module_exists('graphicsmagick_effects')) {
    $path = backdrop_get_path('module', 'graphicsmagick_effects');

    backdrop_uninstall_modules(array('graphicsmagick_effects'));
    backdrop_set_message(
      t(
        'The contributed <em>GraphicsMagick Effects</em> module located at %path is no longer necessary, since its functionality is now provided by the <em>GraphicsMagick</em> module. It is recommended to !operation the <em>GraphicsMagick Effects</em> module from your site.',
        array('!operation' => t('remove'), '%path' => BACKDROP_ROOT . "/$path")
      ),
      'warning'
    );
  }
}

/**
 * Clear the image effect definitions cache.
 *
 * @hook
 */
function graphicsmagick_update_1102(): void {
  // This hook is intentionally left blank. The code has been moved to the
  // next hook, graphicsmagick_update_1103().
}

/**
 * Clear the image effect definitions cache.
 *
 * @hook
 */
function graphicsmagick_update_1103(): void {
  backdrop_static_reset('image_effect_definitions');
  cache()->deletePrefix('image_effect_definitions:');
}


